### ISSUE TITLE
Please sanitize your shell scripts

### ISSUE THREAD

**Issue by StuntsPT** [tiagoantao/lositan#4]
Running prepareLibs.sh before getLibs.sh has led to the script erasing my entire ~/ ... (Fortunately I had a very recent backup).
Line 30 of the script was what killed everything. **Seriously that line is dangerous!**
However, this is obviously not optimal and could be avoided by adding the following line to the beginning of all the shell scripts:

```bash
set -e
```

This will exit the script as soon as the first "cd" errors out and avoid doing a "cd .." afterwards
Please add it so it will not cause grief to anyone else...

**Comment by tiagoantao** [comment]
Lositan is in maintenance more now. This means that no more features will be developed and bugs will be sorted on a case-by-case basis.

This one is a serious bug, therefore I changed the script to stop on error. This is not the best solution but it will be enough to avoid a serious problem.

Sorry for the inconvenience caused. This was a particularly obnoxious bug.

**Comment by StuntsPT** [comment]
Thanks for fixing this.
