### ISSUE TITLE
Lositan running help needed

### ISSUE THREAD

**Issue by dipsaha** [tiagoantao/lositan#5]
I am desperately looking to ways to run 'Lositan' with my microsat data. I am using windows 7 32 bit OS and also separately Windows10 64-bit system. I have tried every means to make the original 'Lositan' get launched using java v. 8. But I run out of all lucks. I came across this offline stuff of 'Lositan', which I have downloaded and extracted in my Windows 7 32-bit OS computer. Tried to run 'runLocal.bat' file and also the 'selwb4.jnlp' file by double-clicking the executables. However, again no luck. 
Maybe I am a novice at running this kind of application in windows.
Can you please help me to run 'offline Lositan' in detailed step by step manner?
Thanks

![image](https://user-images.githubusercontent.com/31880276/41609301-18aca78c-7408-11e8-8207-0b0aab3ad6c1.png)

**Comment by tiagoantao** [comment]
Lositan is not supported anymore. I recommend bayesscan
